askme/urls.py
from django.conf.urls import url
from django.contrib import admin
from askme_app import views

urlpatterns = [
    url(r'^get/', views.post_get_view, name='post_get_view'),
    url(r'^$', views.index, name='index'),
    url(r'^hot/', views.hotQuestions, name='hot'),
    url(r'^tag/(\w+)', views.qustionsByTeg, name='tag'),
    url(r'^question/(\d+)', views.qustionByNumber, name='question'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.login, name='login'),
    url(r'^ask/', views.ask, name='ask'),
    url(r'^base/', views.base, name='base'),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^admin/', admin.site.urls, name='urls'),
    url(r'^page/(\d+)', views.index ),
]

askme_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class QuestionManager(models.Manager):
    def current(self, questionId):
        return self.filter(id=questionId)

    def new(self):
        if (self.count() - 30 >= 0):
            return self.all().order_by('-publicationDate')[:50]
        else:
            return self.all()

    def getHotQuestions(self):
        list = self.annotate(countLikes=models.Count('questionlike__question_id')).order_by('-countLikes')[:5]
        # idList = []
        # for question in list:
        #     idList.append("%s " % question.id)
        # raise Exception(idList)
        return list

    def getQuestionsByTag(self, tagName):
        # raise Exception(Question.objects.filter(tag__name=tagName))
        return Question.objects.filter(tag__name=tagName)

class AnswerManager(models.Manager):
    def getQuestionAnswers(self, question_id):
        return self.filter(question_id=question_id)


class Question(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    text = models.TextField(verbose_name=u'Текст вопроса')
    user = models.ForeignKey(User, default=0, verbose_name='ID юзера')
    publicationDate = models.DateTimeField(auto_now_add=True, verbose_name=u'Дата публикации')
    tag = models.ManyToManyField('Tag', verbose_name=u'Тэги')

    objects = QuestionManager()

    class Meta:
        verbose_name = u'Вопрос'
        verbose_name_plural = u'Вопросы'

    def __unicode__(self):
        return self.title

    def ratio(self):
        return self.questionlike_set.filter(status=True).count() - self.questionlike_set.filter(status=False).count()


class Answer(models.Model):
    text = models.TextField(verbose_name=u'Текст ответа')
    publicationDate = models.DateTimeField(auto_now=True, verbose_name=u'Дата создания ответа')
    user = models.ForeignKey(User, default=0, verbose_name='ID юзера')
    question = models.ForeignKey('Question', on_delete=models.CASCADE, verbose_name='ID вопроса')
    objects = AnswerManager()

    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'

    def __unicode__(self):
        return self.text

    def ratio(self):
        return self.answerlike_set.filter(status=True).count() - self.answerlike_set.filter(status=False).count()


class Questionlike(models.Model):
    user = models.ForeignKey(User, verbose_name=' юзера')
    question = models.ForeignKey('Question', on_delete=models.CASCADE, verbose_name='Номер вопроса')
    status = models.BooleanField(verbose_name='Понравилась запись')

    # objects = QuestionlikeManager()

    class Meta:
        verbose_name = u'Лайк вопроса'
        verbose_name_plural = u'Лайки вопросов'

    def __unicode__(self):
        return 'like' if self.status else 'dislike'


class Answerlike(models.Model):
    user = models.ForeignKey(User, default=0, verbose_name='ID юзера')
    answer = models.ForeignKey('Answer', default=0, on_delete=models.CASCADE, verbose_name='ID ответа')
    status = models.BooleanField(verbose_name='Понравилась запись')

    class Meta:
        verbose_name = u'Лайк ответа'
        verbose_name_plural = u'Лайки ответов'

    def __unicode__(self):
        return 'like' if self.status else 'dislike'


class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'Имя тэга')

    class Meta:
        verbose_name = u'Тэг'
        verbose_name_plural = u'Тэги'

    def __unicode__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=0, verbose_name='ID юзера')
    nick = models.CharField(blank=True, null=True, max_length=50,
                            verbose_name='Ник пользователя')  # убрать blank и null
    avatar = models.ImageField(blank=True, null=True, upload_to='static/img/avatars', default=None,
                               verbose_name='Аватар')

    class Meta:
        verbose_name = u'Профиль'
        verbose_name_plural = u'Профили'

    def __unicode__(self):
        return self.id

askme_app/views.py
from datetime import datetime
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404
from askme_app.models import Question, Answer, Tag, User, Questionlike


# datetime.strftime(datetime.now(), "%Y.%m.%d %H:%M:%S")

def post_get_view(request):
    res_template = '{0}  {1}' + ', '
    response_get = ''
    response_post = ''
    for key, value in request.GET.items():
        response_get += res_template.format(key, value)

    response_post = ''
    try:
        response_post = 'POST: ' + request.POST['login2']
    except KeyError:
        response_post = 'Net takih'
    return render(request, '../templates/getAndPostInDjango.html', {'data': iter([response_get, response_post])})


def paginate(objectsList, request):
    paginator = Paginator(objectsList, 10)  # Show 10 objects per page

    page = request.GET.get('page')
    try:
        response = paginator.page(page)
    except PageNotAnInteger:
        response = paginator.page(1)
    except EmptyPage:
        response = paginator.page(paginator.num_pages)

    return response


def index(request):
    questionList = Question.objects.new()
    return render(request, 'askme/index.html', {'questionList': paginate(questionList, request), })


def hotQuestions(request):
    hotQuestionsList = Question.objects.getHotQuestions()
    return render(request, 'askme/index.html', {'questionList': hotQuestionsList, })


def qustionsByTeg(request, tagName):
    # questionList = []
    # for number in range(1, 2):
    #     questionList.append({'id': number,
    #                          'title': 'QUESTION #%s' % number,
    #                          'text': 'QUESTION BODY and other text'})
    #
    # hotTagsList = ['sql', 'js', 'python', 'django', ]
    # countAnswers = 10

    questionList = Question.objects.getQuestionsByTag(tagName)

    return render(request, 'askme/index.html', {'questionList': questionList,
                                                #'hotTagsList': hotTagsList,
                                                #'countAnswers': countAnswers
                  })


def qustionByNumber(request, number):
    # raise Exception(request.get_raw_uri())
    try:
        questionList = Question.objects.current(number)
    except:
        return Http404
    answersList = Answer.objects.getQuestionAnswers(number)
    current_page = paginate(answersList, request)
    return render(request, 'askme/question.html', {'questionList': questionList,
                                                   'answersList': current_page, })


def login(request):
    return render(request, 'askme/login.html')


def signup(request):
    return render(request, 'askme/signup.html')


def ask(request):
    return render(request, 'askme/ask.html')


def base(request):
    return render(request, 'askme/base.html')


def settings(request):
    return render(request, 'askme/settings.html')

templates/askme/ask.html
{% extends "askme/base.html" %}

{% block content %}
    <div class="row question_head">
        <div class="col-lg-12 question_head__header"><h2>NEW QUESTIONS</h2></div>
    </div>
    <div class="row"><!-- Start body question -->

        <div class="col-lg-1 askme_createQuestion_title">
            Title
        </div>
        <div class="col-lg-11">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Title">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 askme_createQuestion_title">
            Text
        </div>
        <div class="col-lg-11">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <textarea class="form-control askme_textArea_width_100" rows="3"
                              placeholder="Your question"></textarea>
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 askme_createQuestion_title">
            Tags
        </div>
        <div class="col-lg-11">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Title">
                </div>

            </form>
        </div>
    </div> <!-- /Start body question -->

    <div class="row">
        <div class="col-lg-11 col-lg-offset-1">
            <button type="submit" class="btn btn-default">Ask!</button>
        </div>
    </div>
{% endblock %}

templates/askme/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AskMe</title>
    <link href="../../css/reset.css" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="../../css/bootstrap.min.css" rel="stylesheet">
    <link href="../../css/style.css" rel="stylesheet">
</head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">Askme</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search">
                <input type="text" class="form-control askme_nav_input" placeholder="Search...">
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right navbar_inlarge">

                <li class="user_information">
                    <img src="../../img/avatar1.png" class="img-circle askme_topbar_avatar" alt="Avatar">
                    <p class="nickname">Егор Фомичев</p>
                </li>
                <li class="dropdown">
                    <a href="#" style="margin-top: 3px;" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'settings' %}">Settings</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'login' %}">Exit</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!--/.nav -->
</nav>

<div class="container-fluid" style="margin-top: 0px">
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                <div class="col-lg-11 col-lg-offset-1">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-2">
            <div>
                <h2>Tags</h2>
                <div class="popular_tags">
                    <a href="" class="popular_tags_anchor">TARANTOOL</a>
                    <a href="" class="popular_tags_anchor">GUNICORN</a>
                    <a href="" class="popular_tags_anchor">NGINX</a>
                    <a href="" class="popular_tags_anchor">CSS</a><br>
                </div>
            </div>
            <div>
                <h2>Users</h2>
                <div>
                    <ul style="list-style: none;">
                        <li><a href="#">Alex</a></li>
                        <li><a href="#">Mikki</a></li>
                        <li><a href="#">Sam</a></li>
                        <li><a href="#">Rabbit</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div class="col-lg-1"></div>

</div>


<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="../../js/bootstrap.min.js"></script>
</body>
</html>

templates/askme/base_unauthorized_user.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>AskMe</title>
	<link href="../../css/reset.css" rel="stylesheet">

	<!-- Bootstrap -->
	<link href="../../css/bootstrap.min.css" rel="stylesheet">
	<link href="../../css/style.css" rel="stylesheet">
</head>
<body>
	<!-- Static navbar -->
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Askme</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<form class="navbar-form navbar-left" role="search">
					<input type="text" class="form-control askme_nav_input" placeholder="Search...">
					<button type="submit" class="btn btn-default">Search</button>
				</form>
                <ul class="nav navbar-nav navbar-right navbar_inlarge">

					<li class="user_information">
						<a href="/login">Login</a>
					</li>

				</ul>
			</div>
		</div><!--/.nav -->
	</nav>

	<div class="container-fluid" style="margin-top: -20px">
		<div class="row">
			<div class="col-lg-8">
				<div class="row">
					<div class="col-lg-11 col-lg-offset-1">
						{% block content %}{% endblock %}
					</div>
				</div>


			</div>
			<div class="col-lg-1"></div>
			<div class="col-lg-3 askme_tags_panel">
				<div>
					<h2>Tags</h2>
					<div class="popular_tags">
						<a href="" class="popular_tags_anchor">SQL1</a>
						<a href="" class="popular_tags_anchor">TARANTOOL</a>
						<a href="" class="popular_tags_anchor">GUNICORN</a>
						<a href="" class="popular_tags_anchor">NGINX</a>
						<a href="" class="popular_tags_anchor">CSS</a>
					</div>
				</div>
				<div>
					<h2>Users</h2>
					<div>
						<ul style="list-style: none;">
							<li><a href="#">Alex</a></li>
							<li><a href="#">Mikki</a></li>
							<li><a href="#">Sam</a></li>
							<li><a href="#">Rabbit</a></li>
						</ul>
					</div>
				</div>
			</div>

		</div>
	</div>





	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="../../js/bootstrap.min.js"></script>
</body>
</html>

templates/askme/headlinks.html
<div class="row question_head">
    <div class="col-lg-4 question_head__another" style="text-align: justify;">
        <a href="#" style="vertical-align: middle; text-align: justify;">New questions</a>
    </div>
    <div class="col-lg-4 question_head__another" style="text-align: justify;">
        <a href="{% url 'hot' %}" style="vertical-align: middle; text-align: justify;">Hot questions</a>
    </div>
    <div class="col-lg-4 question_head__another" style="text-align: justify;">
        <a href="{% url 'ask' %}" style="vertical-align: middle; text-align: justify;">Ask question</a>
    </div>
</div>

templates/askme/index.html
{% extends "askme/base.html" %}

{% block content %}
    {% include "askme/headlinks.html" %}
    <div>
        {% if questionList %}
            {% for question in questionList %}
                {% include "askme/one_question.html" %}
            {% endfor %}
        {% endif %}
    </div>
    {% include "askme/paginator.html" %}
{% endblock %}

templates/askme/login.html
{% extends "askme/base_unauthorized_user.html" %}

{% block content %}

{#<div class="row"><!-- Start body question -->#}
{#	<div class="col-lg-11 col-lg-offset-2" style="padding-top: 25px;">#}
{#		<p class="text-error" style="color: red;"> Wrong Login or Password </p>#}
{#	</div>#}
{#</div>#}
<div class="row" style="margin-top: 50px;">
	<div class="col-lg-1 askme_createQuestion_title"> <!-- Start body question -->
		Login
	</div>
	<div class="col-lg-10 col-lg-offset-1">
        <div style="color: red; font-size: xx-small;">ERROR</div>
		<form>
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Login">
			</div>

		</form>
	</div>
</div>
<div class="row">
	<div class="col-lg-1 askme_createQuestion_title">
		Password
	</div>
	<div class="col-lg-10 col-lg-offset-1">
        <div style="color: red; font-size: xx-small;">ERROR</div>
		<form>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="Password">
			</div>

		</form>
	</div>
</div> <!-- /Start body question -->

<div class="row">
	<div class="col-lg-10 col-lg-offset-2">
		<button type="submit" class="btn btn-default">Sign In</button>
		<br><br>
		<a href="/signup">Create new accaunt</a>
	</div>
</div>

{% endblock %}

templates/askme/one_answer.html
<div class="row askme_question" sty> <!-- one answer -->
    <div class="col-lg-2">
        <div style="text-align: center;margin-top: 10px; margin-bottom: -10px; max-width: 100%;">{{ answer.user.username }}</div>
        <div style="text-align: center;"><img src="../../img/avatar1.png" style="width: 70px; margin-top: 20%;"></div>
        <div class="row" style="padding-top: 25%">
            <div class="col-lg-4"><a href="#"><span class="glyphicon glyphicon-thumbs-up"></span></a></div>
            <div class="col-lg-4" style="padding-left: 11px;">{{ answer.ratio }}</div>
            <div class="col-lg-4"><a href="#"><span class="glyphicon glyphicon-thumbs-down"></span></a></div>
        </div>
    </div>
    <div class="col-lg-10">
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div class="askme_question_date" style="margin-left: 0px;">
                    date: {{ answer.publicationDate }}
                </div>
            </div>
        </div>
        <hr class="askme_small_margin_hr">
        <div class="row">
            <div class="col-lg-12">
                <div class="askme_question_text">{{ answer.text }}</div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12" style="padding-top: 10px;">
                <label class="checkbox-inline">
                    <input type="checkbox"> Correct
                </label>
            </div>
        </div>
        <br>
    </div>
</div> <!-- /one answer -->

templates/askme/one_question.html
<div class="row askme_question" style="display: flex; align-items: stretch;"> <!-- one question -->
    <div class="col-lg-2">
        <div style="text-align: center;margin-top: 10px; margin-bottom: -10px; max-width: 100%;">{{ question.user.username }}</div>
        <div style="text-align: center;"><img src="http://lorempixel.com/200/200/"
                                              style="width: 70px; margin-top: 20%;"></div>
        <div class="row" style="padding-top: 25%">
            <div class="col-lg-4"><a href="#"><span class="glyphicon glyphicon-thumbs-up"></span></a></div>
            <div class="col-lg-4" style="padding-left: 11px;">{{ question.ratio }}</div>
            <div class="col-lg-4"><a href="#"><span class="glyphicon glyphicon-thumbs-down"></span></a></div>
        </div>
    </div>
    <div class="col-lg-10">
        <div class="row">
            <div class="col-lg-12" style="margin-bottom: 15px">
                <h3 style="margin-bottom: 0px;"><a href="{% url 'question' question.id %}">{{ question.title }}</a></h3>
                <div style="color: lightcoral">
                    date: {{ question.publicationDate }}
                </div>
                <hr class="askme_small_margin_hr">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="askme_question_text">{{ question.text }}</div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">

                <div class="row askme_question_answer_and_tags">
                    <div class="col-lg-3">
                        {#                        <span style="color: lightcoral"> {{ question.answer_set.count }}</span>#}
                        <span style="color: lightcoral; margin-top: 13px;"><span
                                class="glyphicon glyphicon-comment"></span> {{ question.answer_set.count }}</span>
{#                        <button type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-comment"></span> {{ question.answer_set.count }}</button>#}

                    </div>
                    <div class="col-lg-9" style="color: lightcoral">Tags:

                        {% for tag in question.tag.all %}
                            <a href="{% url 'tag' tag %}" class="popular_tags_header">{{ tag }}</a>
                        {% endfor %}

                    </div>
                </div>


            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">

            </div>
        </div>
    </div>
</div> <!-- /one question -->

templates/askme/paginator.html
<div>
    <nav aria-label="Page navigation">


        {% if answersList %}
            <ul class="pagination">
                {% if answersList.has_previous %}
                    <li><a href="?page={{ answersList.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&laquo;</a></li>
                {% endif %}

                {% for num in answersList.paginator.page_range %}
                    {% ifequal num answersList.number %}
                        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                    {% endifequal %}
                {% endfor %}

                {% if answersList.has_next %}
                    <li><a href="?page={{ answersList.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        {% elif questionList %}
            <ul class="pagination">
                {% if questionList.has_previous %}
                    <li><a href="?page={{ questionList.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&laquo;</a></li>
                {% endif %}

                {% for num in questionList.paginator.page_range %}
                    {% ifequal num questionList.number %}
                        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                    {% endifequal %}
                {% endfor %}

                {% if questionList.has_next %}
                    <li><a href="?page={{ questionList.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><a href="#">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}


    </nav>
</div>

templates/askme/popular_tags.html
{% extends "askme/base.html" %}

{% block hotTags %}

{% if hotTagsList %}

{% for hotTag in hotTagsList%}
    <a href="{% url 'qustionsByTeg' hotTag %}" class="popular_tags_anchor">hotTag</a>
{% endfor %}

{% endif%}

{%  endblock %}

templates/askme/question.html
{% extends "askme/base.html" %}

{% block content %}
    {% include "askme/headlinks.html" %}
    <div>
        {% if questionList %}
            {% for question in questionList %}
                {% include "askme/one_question.html" %}
            {% endfor %}
        {% endif %}



        {% if answersList %}
            {% for answer in answersList %}
                {% include "askme/one_answer.html" %}
            {% endfor %}
        {% endif %}

        <hr>
        <div class="row">
            <div class="col-lg-12">
                <form>
                    <div class="form-group">
                    <textarea class="form-control askme_textArea_width_100" rows="4"
                              placeholder="Enter your answer..."></textarea>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <button type="submit" class="btn btn-default">Answer</button>
            </div>
        </div>

    </div>
    {% include "askme/paginator.html" %}
{% endblock %}

templates/askme/settings.html
{% extends "askme/base.html" %}

{% block content %}
    {#    <div class="row"><!-- Start body question -->#}
    {#        <div class="col-lg-10 col-lg-offset-2" style="padding-top: 25px;">#}
    {#            <p class="text-error" style="color: red;"> Wrong Login or Password </p>#}
    {#        </div>#}
    {#    </div>#}

    <div class="row" style="margin-top: 50px;">
        <div class="col-lg-1 askme_createQuestion_title"> <!-- Start body question -->
            Login
        </div>
        <div class="col-lg-10 col-lg-offset-1">
            <div style="color: red; font-size: xx-small;">ERROR</div>

            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Login">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 askme_createQuestion_title"> <!-- Start body question -->
            Email
        </div>
        <div class="col-lg-10 col-lg-offset-1">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Email">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 askme_createQuestion_title"> <!-- Start body question -->
            Nickname
        </div>
        <div class="col-lg-10 col-lg-offset-1">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Nickname">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1 askme_createQuestion_title">
            Password
        </div>
        <div class="col-lg-10 col-lg-offset-1">
            <div style="color: red; font-size: xx-small;">ERROR</div>

            <form>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1">
            Repeat password
        </div>
        <div class="col-lg-10 col-lg-offset-1">
            <form>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password">
                </div>

            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1" style="margin-top: 5px;">
            Choose avatar
        </div>
        <div class="col-lg-8 col-lg-offset-1">
            <div style="color: red; font-size: xx-small;">ERROR</div>
            <form>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Avatar">
                </div>
            </form>
        </div>
        <div class="col-lg-2">
            <form>
                <div class="form-group" style="margin-top: 12px;">
                    <button type="submit" class="btn btn-default">Choose</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-10 col-lg-offset-2">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>

{% endblock %}

templates/getAndPostInDjango.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GET and POST</title>
</head>
<body>
	<p name="method_post"> POST: </p>
	<form action="{% url 'post_get_view' %}" method="POST">
		{% csrf_token %}
		<p>Query: <input name="login2" type="text" value=""></p>
		<p><input type="submit" value="Submit"></p>
	</form>

	{% for x in data %}
		{{ x }}<br>
	{% endfor %}

</body>
</html>